### PR TITLE
Added the tenant folder

### PR DESCRIPTION
**Pull request by athiruma**
## Type of change
Note: Fill **x** in []
- [ ] bug
- [ ] enhancement
- [x] documentation
- [ ] dependencies

## Description

Adding the tenant folder template to add new accounts.

### CODE REVIEW

**Review by ebattat — COMMENTED** [review]
I think that the tenant should be in the following hierarchy:

jenkins/aws/tenant/default/ => current existing folder
jenkins/aws/tenant/Haim
jenkins/aws/tenant/Mikhail

**Comment by athiruma** [comment]
> 

We will maintain our Jenkins file in a separate directory.
Haim/ Mikhail needs to create their own directory in the tenant's folder and can push those changes here.

**Comment by athiruma** [comment]
> I think that the tenant should be in the following hierarchy:
> 
> jenkins/aws/tenant/default/ => current existing folder jenkins/aws/tenant/Haim jenkins/aws/tenant/Mikhail

We will maintain our Jenkins file in a separate directory.
Haim/ Mikhail needs to create their own directory in the tenant's folder and can push those changes here.

**Comment by ebattat** [comment]
@athiruma, current configuration should be under `tenant -> default`
any other tenant configuration should be on different folder name

**Comment by athiruma** [comment]
> @athiruma, current configuration should be under `tenant -> default` any other tenant configuration should be on different folder name

Done.
I am not adding our Jenkins file to this tenant.

**Review by ebattat — APPROVED** [review]

**Pull request merged**
