### PR TITLE
Add the cro flow diagram

### PR DESCRIPTION
**Pull request by athiruma**
Added the cor dia to Git Hub. This will be used on the cloud resource orchestration front-end webpage.

### CODE REVIEW

**Review by ebattat — APPROVED** [review]
/lgtm

**Comment by athiruma** [comment]
@ebattat Can you merge this PR?

**Comment by ebattat** [comment]
@athiruma, no please fix the elasticsearch issue first

**Comment by athiruma** [comment]
@ebattat merge??

**Pull request merged**
