### PR TITLE
Removed the pr opened type in pr.yml

### PR DESCRIPTION
**Pull request by athiruma**
opened type label caused the running the pr multiple times.

### CODE REVIEW

**Review by ebattat — COMMENTED** [review]
@athiruma do you add also the approve job ?

**Comment by athiruma** [comment]
> @athiruma do you add also the approve job ?

What do you mean?

**Comment by ebattat** [comment]
This [Job](https://github.com/redhat-performance/benchmark-runner/blob/f07605a94d32c906b52b09eb3211e6a7412a541e/.github/workflows/Perf_Env_PR_Test_CI.yml#L19-L23)

**Comment by athiruma** [comment]
> This [Job](https://github.com/redhat-performance/benchmark-runner/blob/f07605a94d32c906b52b09eb3211e6a7412a541e/.github/workflows/Perf_Env_PR_Test_CI.yml#L19-L23)

No, ne

> Job

Done

**Pull request merged**
