### PR TITLE
Added the instance type count

### PR DESCRIPTION
**Pull request by athiruma**
Added the instance_type and its count per region

### CODE REVIEW

**Comment by ebattat** [comment]
@athiruma, do we override it every day or count the same one again ?

**Comment by athiruma** [comment]
> @athiruma, do we override it every day or count the same one again ?

no, I implemented this in ec2_run, so we will upload only once.

**Comment by ebattat** [comment]
So for each unique instance ID, we will count only once, right ?

**Comment by athiruma** [comment]
> So for each unique instance ID, we will count only once, right ?

yes right

**Comment by ebattat** [comment]
Do we want to add pytest for it ?

**Review by ebattat — APPROVED** [review]
/LGTM

**Pull request merged**
