### PR TITLE
check tag_value 'owned' when found cluster tag

### PR DESCRIPTION
**Pull request by athiruma**
## Type of change
Note: Fill **x** in []
- [x]  bug
- [ ] enhancement
- [ ] documentation
- [ ] dependencies

## Description
check tag_value 'owned' when found cluster tag. This implies a strict cluster check.
tag looks like - kubernetes.io/cluster/test: Owned

### CODE REVIEW

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the TagClusterResources class to check for the 'owned' tag value when a cluster tag is found. This implements a stricter cluster check as per the issue description.

I also created pull request: https://github.com/redhat-performance/cloud-governance/pull/868


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Review by ebattat — APPROVED** [review]
/LGTM

**Comment by ebattat** [comment]
@athiruma, did you test it ?

**Comment by athiruma** [comment]
> @athiruma, did you test it ?

Yes, We don't have any problem. Here I added one extra check to know the cluster.

**Pull request merged**
