### PR TITLE
[doc-updates]: Minor nit to README.md

### PR DESCRIPTION
**Pull request by krishvoor**
This PR updates the README.md for cloudsensei.
This is minor nit updating the docs accordingly.

### CODE REVIEW

**Comment by krishvoor** [comment]
Hi 👋 @athiruma @ebattat ptal

**Comment by ebattat** [comment]
@krishvoor pls add PR description

**Comment by krishvoor** [comment]
> @krishvoor pls add PR description

Updated, ptal

**Review by athiruma — APPROVED** [review]
LGTM

**Review by ebattat — APPROVED** [review]
/LGTM

**Pull request merged**
