### PR TITLE
Add the unit price to policies

### PR DESCRIPTION
**Pull request by athiruma**
## Type of change
Note: Fill **x** in []
- [ ] bug
- [ ] enhancement
- [x] documentation
- [ ] dependencies

## Description
Added the unit price to missing policies.

### CODE REVIEW

**Review by ebattat — COMMENTED** [review]
Do you plan also to add volume price ?

**Comment by ebattat** [comment]
Can you please add integration test, to verify that we get unit cost properly ?

**Comment by athiruma** [comment]
> Do you plan also to add volume price ?

I added it already to unattached_volume.

**Comment by athiruma** [comment]
> Can you please add integration test, to verify that we get unit cost properly ?

yup, okay.

**Review by ebattat — APPROVED** [review]
/LGTM

**Pull request merged**
